#ifndef __alex_msgs__msg__AlexCommand__idl__
#define __alex_msgs__msg__AlexCommand__idl__

#include "alex_msgs/msg/./OneDOFJointCommand_.idl"
module alex_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Holds desired control commands for Alexander
       */
      @TypeCode(type="alex_msgs::msg::dds_::AlexCommand_")
      struct AlexCommand
      {
        /**
         * Operational commands of the robot
         */
        boolean enable_actuators;
        boolean clear_faults;
        boolean calibrate;
        /**
         * Control state of the robot, 0 is do nothing, 1 is hold position, 2 is user control
         */
        octet robot_control_state;
        unsigned long number_of_joints;
        /**
         * Joint Commands for the robot
         */
        sequence<alex_msgs::msg::dds::OneDOFJointCommand, 50> joint_commands;
        double low_level_master_gain;
      };
    };
  };
};

#endif
