#ifndef __alex_msgs__msg__AlexCommand__idl__
#define __alex_msgs__msg__AlexCommand__idl__

#include "alex_msgs/msg/./OneDOFJointCommand_.idl"
module alex_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Holds desired control commands for Alex
       */
      @TypeCode(type="alex_msgs::msg::dds_::AlexCommand_")
      struct AlexCommand
      {
        /**
         * Requests auto startup, which: requests safe power up, clears faults, enables actuators, and sets robot_control_state to user
         */
        boolean request_auto_startup;
        /**
         * Requests auto shutdown, which: disables actuators and requests safe power down
         */
        boolean request_auto_shutdown;
        /**
         * Requests for safe power up and power down procedures for PMB
         */
        boolean request_safe_power_up;
        boolean request_safe_power_down;
        /**
         * Other individual controls for robot startup procedure
         */
        boolean enable_actuators;
        boolean clear_faults;
        boolean calibrate;
        double low_level_master_gain;
        /**
         * Control state of the robot, 0 is do nothing, 1 is hold position, 2 is user control
         */
        octet robot_control_state;
        /**
         * Joint Commands for the robot
         */
        sequence<alex_msgs::msg::dds::OneDOFJointCommand, 50> joint_commands;
        unsigned long number_of_joints;
      };
    };
  };
};

#endif
