#ifndef __alex_msgs__msg__AlexState__idl__
#define __alex_msgs__msg__AlexState__idl__

#include "alex_msgs/msg/./ForceTorqueState_.idl"
#include "alex_msgs/msg/./IMUState_.idl"
#include "alex_msgs/msg/./OneDOFJointState_.idl"
module alex_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Holds the current state of Alex
       */
      @TypeCode(type="alex_msgs::msg::dds_::AlexState_")
      struct AlexState
      {
        /**
         * General Status
         */
        double time;
        boolean is_faulted;
        boolean is_calibrated;
        boolean are_actuators_enabled;
        boolean safe_power_up_complete;
        boolean safe_power_down_complete;
        double current_low_level_master_gain;
        /**
         * Joint States
         */
        sequence<alex_msgs::msg::dds::OneDOFJointState, 50> joint_states;
        unsigned long number_of_joints;
        /**
         * IMU States
         */
        sequence<alex_msgs::msg::dds::IMUState, 50> imu_states;
        unsigned long number_of_imus;
        /**
         * FT States
         */
        sequence<alex_msgs::msg::dds::ForceTorqueState, 50> ft_states;
        unsigned long number_of_fts;
      };
    };
  };
};

#endif
