#ifndef __alex_msgs__msg__ForceTorqueState__idl__
#define __alex_msgs__msg__ForceTorqueState__idl__

module alex_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Holds current state of the FT sensor
       */
      @TypeCode(type="alex_msgs::msg::dds_::ForceTorqueState_")
      struct ForceTorqueState
      {
        string<32> sensor_name;
        /**
         * Sensor Data
         */
        double force[3];
        double torque[3];
        /**
         * Sensor Status
         */
        boolean is_operational;
      };
    };
  };
};

#endif
