#ifndef __alex_msgs__msg__HardwareStatus__idl__
#define __alex_msgs__msg__HardwareStatus__idl__

#include "alex_msgs/msg/./ROSDeviceStatusProvider_.idl"
module alex_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Holds hardware status info of Alex
       */
      @TypeCode(type="alex_msgs::msg::dds_::HardwareStatus_")
      struct HardwareStatus
      {
        /**
         * Various fault info
         */
        boolean robot_fault;
        boolean motor_fault;
        boolean missed_deadline_fault;
        boolean working_counter_fault;
        boolean bus_over_voltage_fault;
        boolean bus_over_current_fault;
        /**
         * Important EtherCAT Stuff
         */
        unsigned long working_counter_mismatch_count;
        unsigned long missed_deadlines;
        /**
         * Power Management Board Information
         */
        double battery_charge_percentage;
        double estimated_runtime_minutes;
        boolean bus_over_voltage_warning;
        boolean bus_over_current_warning;
        double battery_voltage_volts;
        double battery_current_amps;
        double battery_power_watts;
        double power_supply_voltage_volts;
        double power_supply_current_amps;
        double power_supply_power_watts;
        double motor_bus_voltage_volts;
        double motor_bus_current_amps;
        double motor_bus_power_watts;
        /**
         * Joint States
         */
        sequence<alex_msgs::msg::dds::ROSDeviceStatusProvider, 75> device_status_providers;
      };
    };
  };
};

#endif
