#ifndef __alex_msgs__msg__OneDOFJointState__idl__
#define __alex_msgs__msg__OneDOFJointState__idl__

module alex_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Holds info for each 1DOF controlled Joint
       */
      @TypeCode(type="alex_msgs::msg::dds_::OneDOFJointState_")
      struct OneDOFJointState
      {
        string<35> joint_name;
        /**
         * Joint Data
         */
        double q;
        double qd;
        double tau;
        /**
         * Actuator statuses
         */
        double act_temp;
        boolean is_operational;
      };
    };
  };
};

#endif
