#!/usr/bin/env python3
"""
Assemble the Alex V2 composite URDF parts into single whole-body URDF files.

Each body segment of Alex lives in its own URDF so configurations can be mixed and matched. This script stitches
a fixed set of those parts together (the same way downstream consumers such as ihmc-lab do) and writes the result
next to the parts, so tools that expect a single URDF can load the robot directly.

Outputs (in alex-models/alex_virtual_description/alex_v2_description/urdf):
  alex_v2.wholeBody.urdf                      - full body with cycloidal forearms, no hands
  alex_v2.wholeBody_abilityHands.urdf         - full body with PSYONIC Ability Hands (large)
  alex_v2.wholeBody_convex.urdf               - as wholeBody, with convex hull collision meshes
  alex_v2.wholeBody_abilityHands_convex.urdf  - as wholeBody_abilityHands, with convex hull collision meshes

The default variants use primitive collision shapes (boxes, cylinders, capsules, spheres). The convex variants use
the *_convex part URDFs. The Ability Hands have no convex variant, so both hand URDFs use the same hand parts.

Usage:
  python3 utils/generate_whole_body_urdfs.py          # regenerate the whole-body URDFs
  python3 utils/generate_whole_body_urdfs.py --check  # exit non-zero if the committed files are out of date

The generated files must not be edited by hand. Edit the part URDFs and rerun this script instead.
"""

import argparse
import difflib
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MODELS_ROOT = REPO_ROOT / "alex-models"
V2_URDF_DIR = MODELS_ROOT / "alex_virtual_description" / "alex_v2_description" / "urdf"
HANDS_ROOT = REPO_ROOT / "alex-ros2" / "ihmc_hands_ros2"
ABILITY_HAND_URDF_DIR = HANDS_ROOT / "urdf" / "abilityHand"

BODY_PART_NAMES = ["lowerBody", "head", "leftUpperArm", "leftForearm", "rightUpperArm", "rightForearm"]


def body_parts(suffix: str = "") -> list[Path]:
    """The body part URDFs; suffix selects a collision variant, e.g. "_convex" for the convex hull collision meshes."""
    return [V2_URDF_DIR / f"alex_v2.{name}{suffix}.urdf" for name in BODY_PART_NAMES]


ABILITY_HAND_PARTS = [
    V2_URDF_DIR / "alex_v2.leftAbilityHandAdapter.urdf",
    ABILITY_HAND_URDF_DIR / "ability_hand_left_large.urdf",
    V2_URDF_DIR / "alex_v2.rightAbilityHandAdapter.urdf",
    ABILITY_HAND_URDF_DIR / "ability_hand_right_large.urdf",
]

WHOLE_BODY_URDFS = {
    V2_URDF_DIR / "alex_v2.wholeBody.urdf": body_parts(),
    V2_URDF_DIR / "alex_v2.wholeBody_abilityHands.urdf": body_parts() + ABILITY_HAND_PARTS,
    V2_URDF_DIR / "alex_v2.wholeBody_convex.urdf": body_parts("_convex"),
    V2_URDF_DIR / "alex_v2.wholeBody_abilityHands_convex.urdf": body_parts("_convex") + ABILITY_HAND_PARTS,
}

# Top-level URDF elements carried over from each part. Anything else is ignored.
MERGED_TAGS = ("material", "link", "joint", "transmission", "gazebo")


def display_path(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def merge_parts(parts: list[Path]) -> ET.Element:
    """Concatenate the top-level elements of each part into one <robot>, named after the first part."""
    merged = None
    for part in parts:
        if not part.is_file():
            raise FileNotFoundError(f"Missing URDF part: {display_path(part)}"
                                    + (" (is the ihmc_hands_ros2 submodule checked out?)" if HANDS_ROOT in part.parents else ""))
        part_robot = ET.parse(part).getroot()
        if merged is None:
            merged = ET.Element("robot", part_robot.attrib)
            merged.append(ET.Comment(" AUTO-GENERATED by utils/generate_whole_body_urdfs.py. Do not edit by hand; edit the "
                                     "part URDFs and rerun the script. "))
        merged.append(ET.Comment(f" Part: {display_path(part)} "))
        for element in part_robot:
            if element.tag in MERGED_TAGS:
                merged.append(element)
    return merged


def validate(robot: ET.Element, name: str):
    """Make sure the parts assembled into a single, well-formed kinematic tree."""
    errors = []

    def find_duplicates(tag):
        seen, duplicates = set(), set()
        for element in robot.findall(tag):
            element_name = element.get("name")
            (duplicates if element_name in seen else seen).add(element_name)
        if duplicates:
            errors.append(f"duplicate {tag} names: {sorted(duplicates)}")
        return seen

    links = find_duplicates("link")
    find_duplicates("joint")

    children = set()
    for joint in robot.findall("joint"):
        parent, child = joint.find("parent").get("link"), joint.find("child").get("link")
        for link in (parent, child):
            if link not in links:
                errors.append(f"joint '{joint.get('name')}' references unknown link '{link}'")
        if child in children:
            errors.append(f"link '{child}' has more than one parent joint")
        children.add(child)

    roots = links - children
    if len(roots) != 1:
        errors.append(f"expected exactly one root link, found {sorted(roots)}")

    if errors:
        raise ValueError(f"{name} is not a valid kinematic tree:\n  " + "\n  ".join(errors))


def to_urdf_string(robot: ET.Element) -> str:
    ET.indent(robot, space="  ")
    return '<?xml version="1.0" ?>\n' + ET.tostring(robot, encoding="unicode") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="Do not write anything; fail if a committed whole-body URDF differs from the generated one.")
    args = parser.parse_args()

    out_of_date = []
    for output_path, parts in WHOLE_BODY_URDFS.items():
        robot = merge_parts(parts)
        validate(robot, display_path(output_path))
        generated = to_urdf_string(robot)

        if args.check:
            committed = output_path.read_text(encoding="utf-8") if output_path.is_file() else ""
            if committed != generated:
                out_of_date.append(output_path)
                sys.stdout.writelines(difflib.unified_diff(committed.splitlines(keepends=True),
                                                           generated.splitlines(keepends=True),
                                                           fromfile=f"committed/{display_path(output_path)}",
                                                           tofile=f"generated/{display_path(output_path)}"))
            else:
                print(f"Up to date: {display_path(output_path)}")
        else:
            output_path.write_text(generated, encoding="utf-8")
            print(f"Wrote {display_path(output_path)}")

    if out_of_date:
        print("\nThe following whole-body URDFs are out of sync with their parts:", file=sys.stderr)
        for path in out_of_date:
            print(f"  {display_path(path)}", file=sys.stderr)
        print("Run 'python3 utils/generate_whole_body_urdfs.py' and commit the result.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
