#ifndef __alexander_msgs__msg__ECATDeviceStatus__idl__
#define __alexander_msgs__msg__ECATDeviceStatus__idl__

module alexander_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="alexander_msgs::msg::dds_::ECATDeviceStatus_")
      struct ECATDeviceStatus
      {
        /**
         * Holds the device info and the respective status
         */
        string device_name;
        long alias;
        long position;
        long state;
        boolean is_operational;
      };
    };
  };
};

#endif
