#ifndef __alexander_msgs__msg__HardwareResources__idl__
#define __alexander_msgs__msg__HardwareResources__idl__

module alexander_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Designates the resources to use for hardware
       */
      @TypeCode(type="alexander_msgs::msg::dds_::HardwareResources_")
      struct HardwareResources
      {
        /**
         * Designate the number of xml resources and their names
         */
        unsigned long num_resources;
        /**
         * The directory containing the resources of the desired version of the robot
         */
        string<32> version_directory;
        /**
         * The list of individual XML files comprising the full XML description of the robot
         */
        string xml_resources[9];
        /**
         * The list of individual URDF files comprising the full URDF description of the robot
         */
        string urdf_resources[6];
      };
    };
  };
};

#endif
