#ifndef __alexander_msgs__msg__HardwareResources__idl__
#define __alexander_msgs__msg__HardwareResources__idl__

module alexander_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Designates the resources to use for hardware
       */
      @TypeCode(type="alexander_msgs::msg::dds_::HardwareResources_")
      struct HardwareResources
      {
        /**
         * Designate the number of xml resources
         */
        unsigned long num_xml_resources;
        /**
         * Designate the number of xml resources
         */
        unsigned long num_urdf_resources;
        /**
         * The list of individual XML files comprising the full XML description of the robot
         */
        string xml_resources[11];
        /**
         * The list of individual URDF files comprising the full URDF description of the robot
         */
        string urdf_resources[10];
        /**
         * The directory containing the xml and URDF resources of the desired version of the robot
         */
        string<32> directory;
      };
    };
  };
};

#endif
