#ifndef __alexander_msgs__msg__IMUState__idl__
#define __alexander_msgs__msg__IMUState__idl__

module alexander_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Holds the state of the IMU
       */
      @TypeCode(type="alexander_msgs::msg::dds_::IMUState_")
      struct IMUState
      {
        string<32> sensor_name;
        /**
         * SensorData
         * This is the position of the IMU in the world frame
         */
        double position[3];
        /**
         * This is the orientation of the IMU in the world frame, stored as x, y, z, s
         */
        double quaternion[4];
        /**
         * This is the angular velocity of the IMU in the sensor frame
         */
        double gyroscope[3];
        /**
         * This is the linear acceleration of the IMU in the sensor frame
         */
        double accelerometer[3];
        /**
         * Sensor Status
         */
        long temperature;
        boolean is_operational;
      };
    };
  };
};

#endif
