#ifndef __alexander_msgs__msg__OneDOFJointCommand__idl__
#define __alexander_msgs__msg__OneDOFJointCommand__idl__

module alexander_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Sets the desireds for controlling each 1DOF joint
       */
      @TypeCode(type="alexander_msgs::msg::dds_::OneDOFJointCommand_")
      struct OneDOFJointCommand
      {
        string<32> joint_name;
        /**
         * Joint Desireds
         */
        double q_des;
        double qd_des;
        double tau_des;
        double stiffness;
        double damping;
        double max_position_error;
        double max_velocity_error;
        double max_torque;
        /**
         * Enable Actuator Command
         */
        boolean enable;
        /**
         * Joint control type, 0 is Position, 1 is Velocity, 2 is Effort, 3 disables the control
         */
        octet joint_control_type;
      };
    };
  };
};

#endif
