#ifndef __alex_msgs__msg__IMUState__idl__
#define __alex_msgs__msg__IMUState__idl__

module alex_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Holds the state of the IMU
       */
      @TypeCode(type="alex_msgs::msg::dds_::IMUState_")
      struct IMUState
      {
        string<32> sensor_name;
        /**
         * Sensor Data
         */
        double quaternion[4];
        double gyroscope[3];
        double accelerometer[3];
        /**
         * Sensor Status
         */
        long temperature;
        boolean is_operational;
      };
    };
  };
};

#endif
