# Normalized joystick values [-1.0 1.0]
float64 left_joystick_x_normalized
float64 left_joystick_y_normalized
float64 right_joystick_x_normalized
float64 right_joystick_y_normalized

# Normalized trigger values [-1.0 1.0]
float64 left_trigger_normalized
float64 right_trigger_normalized

# Button 1-4 (right side of controller)
bool button1_pressed
bool button2_pressed
bool button3_pressed
bool button4_pressed

# DPad (left side of controller)
bool button_up_pressed
bool button_down_pressed
bool button_left_pressed
bool button_right_pressed

# E-stop
bool e_stop_pressed
