/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Holds desired control commands for Alex
<p>Source (alex_msgs/AlexCommand):
<pre>{@code
# Holds desired control commands for Alex

# Requests auto startup, which: requests safe power up, clears faults, enables actuators, and sets robot_control_state to user
bool request_auto_startup

# Requests auto shutdown, which: disables actuators and requests safe power down
bool request_auto_shutdown

# Requests for safe power up and power down procedures for PMB
bool request_safe_power_up
bool request_safe_power_down

# Other individual controls for robot startup procedure
bool request_enable_actuators
bool request_disable_actuators
bool clear_faults
bool calibrate
bool servo_actuators
bool unservo_quickly
bool use_requested_master_gain
float64 requested_master_gain

# Option to disable non-critical faults
bool disable_noncritical_faults

# Control state of the robot, 0 is do nothing, 1 is hold position, 2 is user control
byte robot_control_state

# Joint Commands for the robot
OneDOFJointCommand[<=50] joint_commands
uint32 number_of_joints
}</pre>
*/
public class AlexCommand implements ROS2Message<AlexCommand>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::AlexCommand_";

   /**
      Requests auto startup, which: requests safe power up, clears faults, enables actuators, and sets robot_control_state to user
   */
   private boolean request_auto_startup_;
   /**
      Requests auto shutdown, which: disables actuators and requests safe power down
   */
   private boolean request_auto_shutdown_;
   /**
      Requests for safe power up and power down procedures for PMB
   */
   private boolean request_safe_power_up_;
   private boolean request_safe_power_down_;
   /**
      Other individual controls for robot startup procedure
   */
   private boolean request_enable_actuators_;
   private boolean request_disable_actuators_;
   private boolean clear_faults_;
   private boolean calibrate_;
   private boolean servo_actuators_;
   private boolean unservo_quickly_;
   private boolean use_requested_master_gain_;
   private double requested_master_gain_;
   /**
      Option to disable non-critical faults
   */
   private boolean disable_noncritical_faults_;
   /**
      Control state of the robot, 0 is do nothing, 1 is hold position, 2 is user control
   */
   private byte robot_control_state_;
   /**
      Joint Commands for the robot
   */
   private final IDLObjectSequence<alex_msgs.OneDOFJointCommand> joint_commands_;
   private int number_of_joints_;

   public AlexCommand()
   {
      request_auto_startup_ = (boolean) false;
      request_auto_shutdown_ = (boolean) false;
      request_safe_power_up_ = (boolean) false;
      request_safe_power_down_ = (boolean) false;
      request_enable_actuators_ = (boolean) false;
      request_disable_actuators_ = (boolean) false;
      clear_faults_ = (boolean) false;
      calibrate_ = (boolean) false;
      servo_actuators_ = (boolean) false;
      unservo_quickly_ = (boolean) false;
      use_requested_master_gain_ = (boolean) false;
      disable_noncritical_faults_ = (boolean) false;
      joint_commands_ = new IDLObjectSequence<alex_msgs.OneDOFJointCommand>(0, 50, alex_msgs.OneDOFJointCommand.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_auto_startup_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_auto_shutdown_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_safe_power_up_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_safe_power_down_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_enable_actuators_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_disable_actuators_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // clear_faults_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // calibrate_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // servo_actuators_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // unservo_quickly_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // use_requested_master_gain_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // requested_master_gain_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // disable_noncritical_faults_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_control_state_
      currentAlignment += joint_commands_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // number_of_joints_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(request_auto_startup_);
      buffer.writeBoolean(request_auto_shutdown_);
      buffer.writeBoolean(request_safe_power_up_);
      buffer.writeBoolean(request_safe_power_down_);
      buffer.writeBoolean(request_enable_actuators_);
      buffer.writeBoolean(request_disable_actuators_);
      buffer.writeBoolean(clear_faults_);
      buffer.writeBoolean(calibrate_);
      buffer.writeBoolean(servo_actuators_);
      buffer.writeBoolean(unservo_quickly_);
      buffer.writeBoolean(use_requested_master_gain_);
      buffer.writeDouble(requested_master_gain_);
      buffer.writeBoolean(disable_noncritical_faults_);
      buffer.writeByte(robot_control_state_);
      joint_commands_.serialize(buffer);
      buffer.writeInt(number_of_joints_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      request_auto_startup_ = buffer.readBoolean();
      request_auto_shutdown_ = buffer.readBoolean();
      request_safe_power_up_ = buffer.readBoolean();
      request_safe_power_down_ = buffer.readBoolean();
      request_enable_actuators_ = buffer.readBoolean();
      request_disable_actuators_ = buffer.readBoolean();
      clear_faults_ = buffer.readBoolean();
      calibrate_ = buffer.readBoolean();
      servo_actuators_ = buffer.readBoolean();
      unservo_quickly_ = buffer.readBoolean();
      use_requested_master_gain_ = buffer.readBoolean();
      requested_master_gain_ = buffer.readDouble();
      disable_noncritical_faults_ = buffer.readBoolean();
      robot_control_state_ = buffer.readByte();
      joint_commands_.deserialize(buffer);
      number_of_joints_ = buffer.readInt();

   }

   @Override
   public void set(AlexCommand from)
   {
      request_auto_startup_ = from.request_auto_startup_;
      request_auto_shutdown_ = from.request_auto_shutdown_;
      request_safe_power_up_ = from.request_safe_power_up_;
      request_safe_power_down_ = from.request_safe_power_down_;
      request_enable_actuators_ = from.request_enable_actuators_;
      request_disable_actuators_ = from.request_disable_actuators_;
      clear_faults_ = from.clear_faults_;
      calibrate_ = from.calibrate_;
      servo_actuators_ = from.servo_actuators_;
      unservo_quickly_ = from.unservo_quickly_;
      use_requested_master_gain_ = from.use_requested_master_gain_;
      requested_master_gain_ = from.requested_master_gain_;
      disable_noncritical_faults_ = from.disable_noncritical_faults_;
      robot_control_state_ = from.robot_control_state_;
      joint_commands_.set(from.joint_commands_);
      number_of_joints_ = from.number_of_joints_;

   }

   public boolean getRequestAutoStartup()
   {
      return request_auto_startup_;
   }

   public void setRequestAutoStartup(boolean request_auto_startup_)
   {
      this.request_auto_startup_ = request_auto_startup_;
   }

   public boolean getRequestAutoShutdown()
   {
      return request_auto_shutdown_;
   }

   public void setRequestAutoShutdown(boolean request_auto_shutdown_)
   {
      this.request_auto_shutdown_ = request_auto_shutdown_;
   }

   public boolean getRequestSafePowerUp()
   {
      return request_safe_power_up_;
   }

   public void setRequestSafePowerUp(boolean request_safe_power_up_)
   {
      this.request_safe_power_up_ = request_safe_power_up_;
   }

   public boolean getRequestSafePowerDown()
   {
      return request_safe_power_down_;
   }

   public void setRequestSafePowerDown(boolean request_safe_power_down_)
   {
      this.request_safe_power_down_ = request_safe_power_down_;
   }

   public boolean getRequestEnableActuators()
   {
      return request_enable_actuators_;
   }

   public void setRequestEnableActuators(boolean request_enable_actuators_)
   {
      this.request_enable_actuators_ = request_enable_actuators_;
   }

   public boolean getRequestDisableActuators()
   {
      return request_disable_actuators_;
   }

   public void setRequestDisableActuators(boolean request_disable_actuators_)
   {
      this.request_disable_actuators_ = request_disable_actuators_;
   }

   public boolean getClearFaults()
   {
      return clear_faults_;
   }

   public void setClearFaults(boolean clear_faults_)
   {
      this.clear_faults_ = clear_faults_;
   }

   public boolean getCalibrate()
   {
      return calibrate_;
   }

   public void setCalibrate(boolean calibrate_)
   {
      this.calibrate_ = calibrate_;
   }

   public boolean getServoActuators()
   {
      return servo_actuators_;
   }

   public void setServoActuators(boolean servo_actuators_)
   {
      this.servo_actuators_ = servo_actuators_;
   }

   public boolean getUnservoQuickly()
   {
      return unservo_quickly_;
   }

   public void setUnservoQuickly(boolean unservo_quickly_)
   {
      this.unservo_quickly_ = unservo_quickly_;
   }

   public boolean getUseRequestedMasterGain()
   {
      return use_requested_master_gain_;
   }

   public void setUseRequestedMasterGain(boolean use_requested_master_gain_)
   {
      this.use_requested_master_gain_ = use_requested_master_gain_;
   }

   public double getRequestedMasterGain()
   {
      return requested_master_gain_;
   }

   public void setRequestedMasterGain(double requested_master_gain_)
   {
      this.requested_master_gain_ = requested_master_gain_;
   }

   public boolean getDisableNoncriticalFaults()
   {
      return disable_noncritical_faults_;
   }

   public void setDisableNoncriticalFaults(boolean disable_noncritical_faults_)
   {
      this.disable_noncritical_faults_ = disable_noncritical_faults_;
   }

   public byte getRobotControlState()
   {
      return robot_control_state_;
   }

   public void setRobotControlState(byte robot_control_state_)
   {
      this.robot_control_state_ = robot_control_state_;
   }

   public IDLObjectSequence<alex_msgs.OneDOFJointCommand> getJointCommands()
   {
      return joint_commands_;
   }

   public int getNumberOfJoints()
   {
      return number_of_joints_;
   }

   public void setNumberOfJoints(int number_of_joints_)
   {
      this.number_of_joints_ = number_of_joints_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AlexCommand {");
      builder.append("request_auto_startup_=");
      builder.append(request_auto_startup_);
      builder.append("request_auto_shutdown_=");
      builder.append(request_auto_shutdown_);
      builder.append("request_safe_power_up_=");
      builder.append(request_safe_power_up_);
      builder.append("request_safe_power_down_=");
      builder.append(request_safe_power_down_);
      builder.append("request_enable_actuators_=");
      builder.append(request_enable_actuators_);
      builder.append("request_disable_actuators_=");
      builder.append(request_disable_actuators_);
      builder.append("clear_faults_=");
      builder.append(clear_faults_);
      builder.append("calibrate_=");
      builder.append(calibrate_);
      builder.append("servo_actuators_=");
      builder.append(servo_actuators_);
      builder.append("unservo_quickly_=");
      builder.append(unservo_quickly_);
      builder.append("use_requested_master_gain_=");
      builder.append(use_requested_master_gain_);
      builder.append("requested_master_gain_=");
      builder.append(requested_master_gain_);
      builder.append("disable_noncritical_faults_=");
      builder.append(disable_noncritical_faults_);
      builder.append("robot_control_state_=");
      builder.append(robot_control_state_);
      builder.append("joint_commands_=");
      builder.append(joint_commands_);
      builder.append("number_of_joints_=");
      builder.append(number_of_joints_);

      builder.append("}");
      return builder.toString();
   }
}