/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Holds the current state of Alex
<p>Source (alex_msgs/AlexState):
<pre>{@code
# Holds the current state of Alex

# General Status
float64 time
bool is_faulted
bool is_calibrated
bool is_servoing
bool is_unservoing
bool is_servoed

bool are_actuators_enabled
bool safe_power_up_complete
bool safe_power_down_complete
bool auto_startup_complete
bool auto_shutdown_complete
float64 current_low_level_master_gain

# Joint States
OneDOFJointState[<=50] joint_states
uint32 number_of_joints

# IMU States
IMUState[<=50] imu_states
uint32 number_of_imus

# FT States
ForceTorqueState[<=50] ft_states
uint32 number_of_fts
}</pre>
*/
public class AlexState implements ROS2Message<AlexState>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::AlexState_";

   /**
      General Status
   */
   private double time_;
   private boolean is_faulted_;
   private boolean is_calibrated_;
   private boolean is_servoing_;
   private boolean is_unservoing_;
   private boolean is_servoed_;
   private boolean are_actuators_enabled_;
   private boolean safe_power_up_complete_;
   private boolean safe_power_down_complete_;
   private boolean auto_startup_complete_;
   private boolean auto_shutdown_complete_;
   private double current_low_level_master_gain_;
   /**
      Joint States
   */
   private final IDLObjectSequence<alex_msgs.OneDOFJointState> joint_states_;
   private int number_of_joints_;
   /**
      IMU States
   */
   private final IDLObjectSequence<alex_msgs.IMUState> imu_states_;
   private int number_of_imus_;
   /**
      FT States
   */
   private final IDLObjectSequence<alex_msgs.ForceTorqueState> ft_states_;
   private int number_of_fts_;

   public AlexState()
   {
      is_faulted_ = (boolean) false;
      is_calibrated_ = (boolean) false;
      is_servoing_ = (boolean) false;
      is_unservoing_ = (boolean) false;
      is_servoed_ = (boolean) false;
      are_actuators_enabled_ = (boolean) false;
      safe_power_up_complete_ = (boolean) false;
      safe_power_down_complete_ = (boolean) false;
      auto_startup_complete_ = (boolean) false;
      auto_shutdown_complete_ = (boolean) false;
      joint_states_ = new IDLObjectSequence<alex_msgs.OneDOFJointState>(0, 50, alex_msgs.OneDOFJointState.class);
      imu_states_ = new IDLObjectSequence<alex_msgs.IMUState>(0, 50, alex_msgs.IMUState.class);
      ft_states_ = new IDLObjectSequence<alex_msgs.ForceTorqueState>(0, 50, alex_msgs.ForceTorqueState.class);

   }

   public AlexState(AlexState from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // time_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_faulted_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_calibrated_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_servoing_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_unservoing_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_servoed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // are_actuators_enabled_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // safe_power_up_complete_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // safe_power_down_complete_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // auto_startup_complete_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // auto_shutdown_complete_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // current_low_level_master_gain_
      currentAlignment += joint_states_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // number_of_joints_
      currentAlignment += imu_states_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // number_of_imus_
      currentAlignment += ft_states_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // number_of_fts_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(time_);
      buffer.writeBoolean(is_faulted_);
      buffer.writeBoolean(is_calibrated_);
      buffer.writeBoolean(is_servoing_);
      buffer.writeBoolean(is_unservoing_);
      buffer.writeBoolean(is_servoed_);
      buffer.writeBoolean(are_actuators_enabled_);
      buffer.writeBoolean(safe_power_up_complete_);
      buffer.writeBoolean(safe_power_down_complete_);
      buffer.writeBoolean(auto_startup_complete_);
      buffer.writeBoolean(auto_shutdown_complete_);
      buffer.writeDouble(current_low_level_master_gain_);
      joint_states_.serialize(buffer);
      buffer.writeInt(number_of_joints_);
      imu_states_.serialize(buffer);
      buffer.writeInt(number_of_imus_);
      ft_states_.serialize(buffer);
      buffer.writeInt(number_of_fts_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      time_ = buffer.readDouble();
      is_faulted_ = buffer.readBoolean();
      is_calibrated_ = buffer.readBoolean();
      is_servoing_ = buffer.readBoolean();
      is_unservoing_ = buffer.readBoolean();
      is_servoed_ = buffer.readBoolean();
      are_actuators_enabled_ = buffer.readBoolean();
      safe_power_up_complete_ = buffer.readBoolean();
      safe_power_down_complete_ = buffer.readBoolean();
      auto_startup_complete_ = buffer.readBoolean();
      auto_shutdown_complete_ = buffer.readBoolean();
      current_low_level_master_gain_ = buffer.readDouble();
      joint_states_.deserialize(buffer);
      number_of_joints_ = buffer.readInt();
      imu_states_.deserialize(buffer);
      number_of_imus_ = buffer.readInt();
      ft_states_.deserialize(buffer);
      number_of_fts_ = buffer.readInt();

   }

   @Override
   public void set(AlexState from)
   {
      time_ = from.time_;
      is_faulted_ = from.is_faulted_;
      is_calibrated_ = from.is_calibrated_;
      is_servoing_ = from.is_servoing_;
      is_unservoing_ = from.is_unservoing_;
      is_servoed_ = from.is_servoed_;
      are_actuators_enabled_ = from.are_actuators_enabled_;
      safe_power_up_complete_ = from.safe_power_up_complete_;
      safe_power_down_complete_ = from.safe_power_down_complete_;
      auto_startup_complete_ = from.auto_startup_complete_;
      auto_shutdown_complete_ = from.auto_shutdown_complete_;
      current_low_level_master_gain_ = from.current_low_level_master_gain_;
      joint_states_.set(from.joint_states_);
      number_of_joints_ = from.number_of_joints_;
      imu_states_.set(from.imu_states_);
      number_of_imus_ = from.number_of_imus_;
      ft_states_.set(from.ft_states_);
      number_of_fts_ = from.number_of_fts_;

   }

   public double getTime()
   {
      return time_;
   }

   public void setTime(double time_)
   {
      this.time_ = time_;
   }

   public boolean getIsFaulted()
   {
      return is_faulted_;
   }

   public void setIsFaulted(boolean is_faulted_)
   {
      this.is_faulted_ = is_faulted_;
   }

   public boolean getIsCalibrated()
   {
      return is_calibrated_;
   }

   public void setIsCalibrated(boolean is_calibrated_)
   {
      this.is_calibrated_ = is_calibrated_;
   }

   public boolean getIsServoing()
   {
      return is_servoing_;
   }

   public void setIsServoing(boolean is_servoing_)
   {
      this.is_servoing_ = is_servoing_;
   }

   public boolean getIsUnservoing()
   {
      return is_unservoing_;
   }

   public void setIsUnservoing(boolean is_unservoing_)
   {
      this.is_unservoing_ = is_unservoing_;
   }

   public boolean getIsServoed()
   {
      return is_servoed_;
   }

   public void setIsServoed(boolean is_servoed_)
   {
      this.is_servoed_ = is_servoed_;
   }

   public boolean getAreActuatorsEnabled()
   {
      return are_actuators_enabled_;
   }

   public void setAreActuatorsEnabled(boolean are_actuators_enabled_)
   {
      this.are_actuators_enabled_ = are_actuators_enabled_;
   }

   public boolean getSafePowerUpComplete()
   {
      return safe_power_up_complete_;
   }

   public void setSafePowerUpComplete(boolean safe_power_up_complete_)
   {
      this.safe_power_up_complete_ = safe_power_up_complete_;
   }

   public boolean getSafePowerDownComplete()
   {
      return safe_power_down_complete_;
   }

   public void setSafePowerDownComplete(boolean safe_power_down_complete_)
   {
      this.safe_power_down_complete_ = safe_power_down_complete_;
   }

   public boolean getAutoStartupComplete()
   {
      return auto_startup_complete_;
   }

   public void setAutoStartupComplete(boolean auto_startup_complete_)
   {
      this.auto_startup_complete_ = auto_startup_complete_;
   }

   public boolean getAutoShutdownComplete()
   {
      return auto_shutdown_complete_;
   }

   public void setAutoShutdownComplete(boolean auto_shutdown_complete_)
   {
      this.auto_shutdown_complete_ = auto_shutdown_complete_;
   }

   public double getCurrentLowLevelMasterGain()
   {
      return current_low_level_master_gain_;
   }

   public void setCurrentLowLevelMasterGain(double current_low_level_master_gain_)
   {
      this.current_low_level_master_gain_ = current_low_level_master_gain_;
   }

   public IDLObjectSequence<alex_msgs.OneDOFJointState> getJointStates()
   {
      return joint_states_;
   }

   public int getNumberOfJoints()
   {
      return number_of_joints_;
   }

   public void setNumberOfJoints(int number_of_joints_)
   {
      this.number_of_joints_ = number_of_joints_;
   }

   public IDLObjectSequence<alex_msgs.IMUState> getImuStates()
   {
      return imu_states_;
   }

   public int getNumberOfImus()
   {
      return number_of_imus_;
   }

   public void setNumberOfImus(int number_of_imus_)
   {
      this.number_of_imus_ = number_of_imus_;
   }

   public IDLObjectSequence<alex_msgs.ForceTorqueState> getFtStates()
   {
      return ft_states_;
   }

   public int getNumberOfFts()
   {
      return number_of_fts_;
   }

   public void setNumberOfFts(int number_of_fts_)
   {
      this.number_of_fts_ = number_of_fts_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AlexState {");
      builder.append("time_=");
      builder.append(time_);
      builder.append("is_faulted_=");
      builder.append(is_faulted_);
      builder.append("is_calibrated_=");
      builder.append(is_calibrated_);
      builder.append("is_servoing_=");
      builder.append(is_servoing_);
      builder.append("is_unservoing_=");
      builder.append(is_unservoing_);
      builder.append("is_servoed_=");
      builder.append(is_servoed_);
      builder.append("are_actuators_enabled_=");
      builder.append(are_actuators_enabled_);
      builder.append("safe_power_up_complete_=");
      builder.append(safe_power_up_complete_);
      builder.append("safe_power_down_complete_=");
      builder.append(safe_power_down_complete_);
      builder.append("auto_startup_complete_=");
      builder.append(auto_startup_complete_);
      builder.append("auto_shutdown_complete_=");
      builder.append(auto_shutdown_complete_);
      builder.append("current_low_level_master_gain_=");
      builder.append(current_low_level_master_gain_);
      builder.append("joint_states_=");
      builder.append(joint_states_);
      builder.append("number_of_joints_=");
      builder.append(number_of_joints_);
      builder.append("imu_states_=");
      builder.append(imu_states_);
      builder.append("number_of_imus_=");
      builder.append(number_of_imus_);
      builder.append("ft_states_=");
      builder.append(ft_states_);
      builder.append("number_of_fts_=");
      builder.append(number_of_fts_);

      builder.append("}");
      return builder.toString();
   }
}