/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Pre-processed depth observation for the fixed-neck / active-neck transformer nav policies.
Published by the Isaac Sim DDS bridge (and later the real perception stack) already in the
POLICY's format: cropped, resampled and sanitized exactly like training
(nan/inf -> 6 m, clamp [0, 6], divided by 6 — so values are in [0, 1], 1.0 = FAR).

head_depth : head camera center crop -> 24x32, row-major        (768 values)
chest_depth: chest camera full frame -> 12x16, row-major        (192 values)

The training contract is a fresh frame every 20 ms policy step (update_period 0.02);
the consumer holds the last frame if a tick is missed and treats never-received as
all-FAR (1.0 everywhere).
<p>Source (alex_msgs/DepthObservation):
<pre>{@code
# Pre-processed depth observation for the fixed-neck / active-neck transformer nav policies.
# Published by the Isaac Sim DDS bridge (and later the real perception stack) already in the
# POLICY's format: cropped, resampled and sanitized exactly like training
# (nan/inf -> 6 m, clamp [0, 6], divided by 6 — so values are in [0, 1], 1.0 = FAR).
#
# head_depth : head camera center crop -> 24x32, row-major        (768 values)
# chest_depth: chest camera full frame -> 12x16, row-major        (192 values)
#
# The training contract is a fresh frame every 20 ms policy step (update_period 0.02);
# the consumer holds the last frame if a tick is missed and treats never-received as
# all-FAR (1.0 everywhere).

uint32 sequence_number

# Publisher-side sim/wall time of the frame, seconds (for staleness accounting)
float64 frame_time

float32[768] head_depth
float32[192] chest_depth
}</pre>
*/
public class DepthObservation implements ROS2Message<DepthObservation>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::DepthObservation_";

   private int sequence_number_;
   /**
      Publisher-side sim/wall time of the frame, seconds (for staleness accounting)
   */
   private double frame_time_;
   private final float[] head_depth_;
   private final float[] chest_depth_;

   public DepthObservation()
   {
      head_depth_ = new float[768];
      chest_depth_ = new float[192];

   }

   public DepthObservation(DepthObservation from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // sequence_number_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // frame_time_
      currentAlignment += (768 * 4) + CDRBuffer.alignment(currentAlignment, (768 * 4)); // head_depth_
      currentAlignment += (192 * 4) + CDRBuffer.alignment(currentAlignment, (192 * 4)); // chest_depth_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(sequence_number_);
      buffer.writeDouble(frame_time_);
      for (int i = 0; i < head_depth_.length; ++i)
      {
         buffer.writeFloat(head_depth_[i]);
      }
      for (int i = 0; i < chest_depth_.length; ++i)
      {
         buffer.writeFloat(chest_depth_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_number_ = buffer.readInt();
      frame_time_ = buffer.readDouble();
      for (int i = 0; i < head_depth_.length; ++i)
      {
         head_depth_[i] = buffer.readFloat();
      }
      for (int i = 0; i < chest_depth_.length; ++i)
      {
         chest_depth_[i] = buffer.readFloat();
      }

   }

   @Override
   public void set(DepthObservation from)
   {
      sequence_number_ = from.sequence_number_;
      frame_time_ = from.frame_time_;
      for (int i = 0; i < head_depth_.length; ++i)
      {
         head_depth_[i] = from.head_depth_[i];
      }
      for (int i = 0; i < chest_depth_.length; ++i)
      {
         chest_depth_[i] = from.chest_depth_[i];
      }

   }

   public int getSequenceNumber()
   {
      return sequence_number_;
   }

   public void setSequenceNumber(int sequence_number_)
   {
      this.sequence_number_ = sequence_number_;
   }

   public double getFrameTime()
   {
      return frame_time_;
   }

   public void setFrameTime(double frame_time_)
   {
      this.frame_time_ = frame_time_;
   }

   public float[] getHeadDepth()
   {
      return head_depth_;
   }

   public float[] getChestDepth()
   {
      return chest_depth_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("DepthObservation {");
      builder.append("sequence_number_=");
      builder.append(sequence_number_);
      builder.append("frame_time_=");
      builder.append(frame_time_);
      builder.append("head_depth_=");
      builder.append(java.util.Arrays.toString(head_depth_));
      builder.append("chest_depth_=");
      builder.append(java.util.Arrays.toString(chest_depth_));

      builder.append("}");
      return builder.toString();
   }
}