/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Holds current state of the FT sensor
<p>Source (alex_msgs/ForceTorqueState):
<pre>{@code
# Holds current state of the FT sensor

string<=32 sensor_name

# Sensor Data
float64[3] force
float64[3] torque

# Sensor Status
bool is_operational}</pre>
*/
public class ForceTorqueState implements ROS2Message<ForceTorqueState>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::ForceTorqueState_";

   // Note: The length of this string should not exceed 32 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder sensor_name_;
   /**
      Sensor Data
   */
   private final double[] force_;
   private final double[] torque_;
   /**
      Sensor Status
   */
   private boolean is_operational_;

   public ForceTorqueState()
   {
      sensor_name_ = new StringBuilder(32);
      force_ = new double[3];
      torque_ = new double[3];
      is_operational_ = (boolean) false;

   }

   public ForceTorqueState(ForceTorqueState from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * sensor_name_.length()) + 1; // sensor_name_
      currentAlignment += (3 * 8) + CDRBuffer.alignment(currentAlignment, (3 * 8)); // force_
      currentAlignment += (3 * 8) + CDRBuffer.alignment(currentAlignment, (3 * 8)); // torque_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_operational_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(sensor_name_);
      for (int i = 0; i < force_.length; ++i)
      {
         buffer.writeDouble(force_[i]);
      }
      for (int i = 0; i < torque_.length; ++i)
      {
         buffer.writeDouble(torque_[i]);
      }
      buffer.writeBoolean(is_operational_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(sensor_name_);
      for (int i = 0; i < force_.length; ++i)
      {
         force_[i] = buffer.readDouble();
      }
      for (int i = 0; i < torque_.length; ++i)
      {
         torque_[i] = buffer.readDouble();
      }
      is_operational_ = buffer.readBoolean();

   }

   @Override
   public void set(ForceTorqueState from)
   {
      sensor_name_.delete(0, sensor_name_.length());
      sensor_name_.insert(0, from.sensor_name_);
      for (int i = 0; i < force_.length; ++i)
      {
         force_[i] = from.force_[i];
      }
      for (int i = 0; i < torque_.length; ++i)
      {
         torque_[i] = from.torque_[i];
      }
      is_operational_ = from.is_operational_;

   }

   public StringBuilder getSensorName()
   {
      return sensor_name_;
   }

   public java.lang.String getSensorNameAsString()
   {
      return sensor_name_.toString();
   }

   public void setSensorName(java.lang.String s)
   {
      this.sensor_name_.delete(0, this.sensor_name_.length());
      this.sensor_name_.insert(0, s);
   }
   public double[] getForce()
   {
      return force_;
   }

   public double[] getTorque()
   {
      return torque_;
   }

   public boolean getIsOperational()
   {
      return is_operational_;
   }

   public void setIsOperational(boolean is_operational_)
   {
      this.is_operational_ = is_operational_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ForceTorqueState {");
      builder.append("sensor_name_=");
      builder.append(sensor_name_.toString());
      builder.append("force_=");
      builder.append(java.util.Arrays.toString(force_));
      builder.append("torque_=");
      builder.append(java.util.Arrays.toString(torque_));
      builder.append("is_operational_=");
      builder.append(is_operational_);

      builder.append("}");
      return builder.toString();
   }
}