/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (alex_msgs/FortRoboticsRCHandheldState):
<pre>{@code
# Normalized joystick values [-1.0 1.0]
float64 left_joystick_x_normalized
float64 left_joystick_y_normalized
float64 right_joystick_x_normalized
float64 right_joystick_y_normalized

# Normalized trigger values [-1.0 1.0]
float64 left_trigger_normalized
float64 right_trigger_normalized

# Button 1-4 (right side of controller)
bool button1_pressed
bool button2_pressed
bool button3_pressed
bool button4_pressed

# DPad (left side of controller)
bool button_up_pressed
bool button_down_pressed
bool button_left_pressed
bool button_right_pressed

# E-stop
bool e_stop_pressed

# Battery
uint16 battery_level
}</pre>
*/
public class FortRoboticsRCHandheldState implements ROS2Message<FortRoboticsRCHandheldState>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::FortRoboticsRCHandheldState_";

   /**
      Normalized joystick values [-1.0 1.0]
   */
   private double left_joystick_x_normalized_;
   private double left_joystick_y_normalized_;
   private double right_joystick_x_normalized_;
   private double right_joystick_y_normalized_;
   /**
      Normalized trigger values [-1.0 1.0]
   */
   private double left_trigger_normalized_;
   private double right_trigger_normalized_;
   /**
      Button 1-4 (right side of controller)
   */
   private boolean button1_pressed_;
   private boolean button2_pressed_;
   private boolean button3_pressed_;
   private boolean button4_pressed_;
   /**
      DPad (left side of controller)
   */
   private boolean button_up_pressed_;
   private boolean button_down_pressed_;
   private boolean button_left_pressed_;
   private boolean button_right_pressed_;
   /**
      E-stop
   */
   private boolean e_stop_pressed_;
   /**
      Battery
   */
   private int battery_level_;

   public FortRoboticsRCHandheldState()
   {
      button1_pressed_ = (boolean) false;
      button2_pressed_ = (boolean) false;
      button3_pressed_ = (boolean) false;
      button4_pressed_ = (boolean) false;
      button_up_pressed_ = (boolean) false;
      button_down_pressed_ = (boolean) false;
      button_left_pressed_ = (boolean) false;
      button_right_pressed_ = (boolean) false;
      e_stop_pressed_ = (boolean) false;

   }

   public FortRoboticsRCHandheldState(FortRoboticsRCHandheldState from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // left_joystick_x_normalized_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // left_joystick_y_normalized_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // right_joystick_x_normalized_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // right_joystick_y_normalized_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // left_trigger_normalized_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // right_trigger_normalized_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // button1_pressed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // button2_pressed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // button3_pressed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // button4_pressed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // button_up_pressed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // button_down_pressed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // button_left_pressed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // button_right_pressed_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // e_stop_pressed_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // battery_level_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(left_joystick_x_normalized_);
      buffer.writeDouble(left_joystick_y_normalized_);
      buffer.writeDouble(right_joystick_x_normalized_);
      buffer.writeDouble(right_joystick_y_normalized_);
      buffer.writeDouble(left_trigger_normalized_);
      buffer.writeDouble(right_trigger_normalized_);
      buffer.writeBoolean(button1_pressed_);
      buffer.writeBoolean(button2_pressed_);
      buffer.writeBoolean(button3_pressed_);
      buffer.writeBoolean(button4_pressed_);
      buffer.writeBoolean(button_up_pressed_);
      buffer.writeBoolean(button_down_pressed_);
      buffer.writeBoolean(button_left_pressed_);
      buffer.writeBoolean(button_right_pressed_);
      buffer.writeBoolean(e_stop_pressed_);
      buffer.writeUInt16(battery_level_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      left_joystick_x_normalized_ = buffer.readDouble();
      left_joystick_y_normalized_ = buffer.readDouble();
      right_joystick_x_normalized_ = buffer.readDouble();
      right_joystick_y_normalized_ = buffer.readDouble();
      left_trigger_normalized_ = buffer.readDouble();
      right_trigger_normalized_ = buffer.readDouble();
      button1_pressed_ = buffer.readBoolean();
      button2_pressed_ = buffer.readBoolean();
      button3_pressed_ = buffer.readBoolean();
      button4_pressed_ = buffer.readBoolean();
      button_up_pressed_ = buffer.readBoolean();
      button_down_pressed_ = buffer.readBoolean();
      button_left_pressed_ = buffer.readBoolean();
      button_right_pressed_ = buffer.readBoolean();
      e_stop_pressed_ = buffer.readBoolean();
      battery_level_ = buffer.readUInt16();

   }

   @Override
   public void set(FortRoboticsRCHandheldState from)
   {
      left_joystick_x_normalized_ = from.left_joystick_x_normalized_;
      left_joystick_y_normalized_ = from.left_joystick_y_normalized_;
      right_joystick_x_normalized_ = from.right_joystick_x_normalized_;
      right_joystick_y_normalized_ = from.right_joystick_y_normalized_;
      left_trigger_normalized_ = from.left_trigger_normalized_;
      right_trigger_normalized_ = from.right_trigger_normalized_;
      button1_pressed_ = from.button1_pressed_;
      button2_pressed_ = from.button2_pressed_;
      button3_pressed_ = from.button3_pressed_;
      button4_pressed_ = from.button4_pressed_;
      button_up_pressed_ = from.button_up_pressed_;
      button_down_pressed_ = from.button_down_pressed_;
      button_left_pressed_ = from.button_left_pressed_;
      button_right_pressed_ = from.button_right_pressed_;
      e_stop_pressed_ = from.e_stop_pressed_;
      battery_level_ = from.battery_level_;

   }

   public double getLeftJoystickXNormalized()
   {
      return left_joystick_x_normalized_;
   }

   public void setLeftJoystickXNormalized(double left_joystick_x_normalized_)
   {
      this.left_joystick_x_normalized_ = left_joystick_x_normalized_;
   }

   public double getLeftJoystickYNormalized()
   {
      return left_joystick_y_normalized_;
   }

   public void setLeftJoystickYNormalized(double left_joystick_y_normalized_)
   {
      this.left_joystick_y_normalized_ = left_joystick_y_normalized_;
   }

   public double getRightJoystickXNormalized()
   {
      return right_joystick_x_normalized_;
   }

   public void setRightJoystickXNormalized(double right_joystick_x_normalized_)
   {
      this.right_joystick_x_normalized_ = right_joystick_x_normalized_;
   }

   public double getRightJoystickYNormalized()
   {
      return right_joystick_y_normalized_;
   }

   public void setRightJoystickYNormalized(double right_joystick_y_normalized_)
   {
      this.right_joystick_y_normalized_ = right_joystick_y_normalized_;
   }

   public double getLeftTriggerNormalized()
   {
      return left_trigger_normalized_;
   }

   public void setLeftTriggerNormalized(double left_trigger_normalized_)
   {
      this.left_trigger_normalized_ = left_trigger_normalized_;
   }

   public double getRightTriggerNormalized()
   {
      return right_trigger_normalized_;
   }

   public void setRightTriggerNormalized(double right_trigger_normalized_)
   {
      this.right_trigger_normalized_ = right_trigger_normalized_;
   }

   public boolean getButton1Pressed()
   {
      return button1_pressed_;
   }

   public void setButton1Pressed(boolean button1_pressed_)
   {
      this.button1_pressed_ = button1_pressed_;
   }

   public boolean getButton2Pressed()
   {
      return button2_pressed_;
   }

   public void setButton2Pressed(boolean button2_pressed_)
   {
      this.button2_pressed_ = button2_pressed_;
   }

   public boolean getButton3Pressed()
   {
      return button3_pressed_;
   }

   public void setButton3Pressed(boolean button3_pressed_)
   {
      this.button3_pressed_ = button3_pressed_;
   }

   public boolean getButton4Pressed()
   {
      return button4_pressed_;
   }

   public void setButton4Pressed(boolean button4_pressed_)
   {
      this.button4_pressed_ = button4_pressed_;
   }

   public boolean getButtonUpPressed()
   {
      return button_up_pressed_;
   }

   public void setButtonUpPressed(boolean button_up_pressed_)
   {
      this.button_up_pressed_ = button_up_pressed_;
   }

   public boolean getButtonDownPressed()
   {
      return button_down_pressed_;
   }

   public void setButtonDownPressed(boolean button_down_pressed_)
   {
      this.button_down_pressed_ = button_down_pressed_;
   }

   public boolean getButtonLeftPressed()
   {
      return button_left_pressed_;
   }

   public void setButtonLeftPressed(boolean button_left_pressed_)
   {
      this.button_left_pressed_ = button_left_pressed_;
   }

   public boolean getButtonRightPressed()
   {
      return button_right_pressed_;
   }

   public void setButtonRightPressed(boolean button_right_pressed_)
   {
      this.button_right_pressed_ = button_right_pressed_;
   }

   public boolean getEStopPressed()
   {
      return e_stop_pressed_;
   }

   public void setEStopPressed(boolean e_stop_pressed_)
   {
      this.e_stop_pressed_ = e_stop_pressed_;
   }

   public int getBatteryLevel()
   {
      return battery_level_;
   }

   public void setBatteryLevel(int battery_level_)
   {
      this.battery_level_ = battery_level_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("FortRoboticsRCHandheldState {");
      builder.append("left_joystick_x_normalized_=");
      builder.append(left_joystick_x_normalized_);
      builder.append("left_joystick_y_normalized_=");
      builder.append(left_joystick_y_normalized_);
      builder.append("right_joystick_x_normalized_=");
      builder.append(right_joystick_x_normalized_);
      builder.append("right_joystick_y_normalized_=");
      builder.append(right_joystick_y_normalized_);
      builder.append("left_trigger_normalized_=");
      builder.append(left_trigger_normalized_);
      builder.append("right_trigger_normalized_=");
      builder.append(right_trigger_normalized_);
      builder.append("button1_pressed_=");
      builder.append(button1_pressed_);
      builder.append("button2_pressed_=");
      builder.append(button2_pressed_);
      builder.append("button3_pressed_=");
      builder.append(button3_pressed_);
      builder.append("button4_pressed_=");
      builder.append(button4_pressed_);
      builder.append("button_up_pressed_=");
      builder.append(button_up_pressed_);
      builder.append("button_down_pressed_=");
      builder.append(button_down_pressed_);
      builder.append("button_left_pressed_=");
      builder.append(button_left_pressed_);
      builder.append("button_right_pressed_=");
      builder.append(button_right_pressed_);
      builder.append("e_stop_pressed_=");
      builder.append(e_stop_pressed_);
      builder.append("battery_level_=");
      builder.append(battery_level_);

      builder.append("}");
      return builder.toString();
   }
}