/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Designates the resources to use for hardware
<p>Source (alex_msgs/HardwareResources):
<pre>{@code
# Designates the resources to use for hardware

# Designate the number of xml resources
uint32 num_xml_resources

# Designate the number of xml resources
uint32 num_urdf_resources

# The list of individual XML files comprising the full XML description of the robot
string<=32[11] xml_resources

# The list of individual URDF files comprising the full URDF description of the robot
string<=32[10] urdf_resources

# The directory containing the xml and URDF resources of the desired version of the robot
string<=32 directory}</pre>
*/
public class HardwareResources implements ROS2Message<HardwareResources>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::HardwareResources_";

   /**
      Designate the number of xml resources
   */
   private int num_xml_resources_;
   /**
      Designate the number of xml resources
   */
   private int num_urdf_resources_;
   /**
      The list of individual XML files comprising the full XML description of the robot
   */
   // Note: The length of each string in this sequence should not exceed 32 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder[] xml_resources_;
   /**
      The list of individual URDF files comprising the full URDF description of the robot
   */
   // Note: The length of each string in this sequence should not exceed 32 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder[] urdf_resources_;
   /**
      The directory containing the xml and URDF resources of the desired version of the robot
   */
   // Note: The length of this string should not exceed 32 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder directory_;

   public HardwareResources()
   {
      xml_resources_ = new StringBuilder[11];
      // xml_resources is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < xml_resources_.length; ++i)
      {
         xml_resources_[i] = new StringBuilder(32);
      }
      urdf_resources_ = new StringBuilder[10];
      // urdf_resources is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < urdf_resources_.length; ++i)
      {
         urdf_resources_[i] = new StringBuilder(32);
      }
      directory_ = new StringBuilder(32);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // num_xml_resources_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // num_urdf_resources_
      for (int i = 0; i < xml_resources_.length; ++i)
      {
         currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * xml_resources_[i].length()) + 1; // xml_resources_[i]
      }
      for (int i = 0; i < urdf_resources_.length; ++i)
      {
         currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * urdf_resources_[i].length()) + 1; // urdf_resources_[i]
      }
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * directory_.length()) + 1; // directory_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(num_xml_resources_);
      buffer.writeInt(num_urdf_resources_);
      for (int i = 0; i < xml_resources_.length; ++i)
      {
         buffer.writeString(xml_resources_[i]);
      }
      for (int i = 0; i < urdf_resources_.length; ++i)
      {
         buffer.writeString(urdf_resources_[i]);
      }
      buffer.writeString(directory_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      num_xml_resources_ = buffer.readInt();
      num_urdf_resources_ = buffer.readInt();
      for (int i = 0; i < xml_resources_.length; ++i)
      {
         buffer.readString(xml_resources_[i]);
      }
      for (int i = 0; i < urdf_resources_.length; ++i)
      {
         buffer.readString(urdf_resources_[i]);
      }
      buffer.readString(directory_);

   }

   @Override
   public void set(HardwareResources from)
   {
      num_xml_resources_ = from.num_xml_resources_;
      num_urdf_resources_ = from.num_urdf_resources_;
      for (int i = 0; i < xml_resources_.length; ++i)
      {
         xml_resources_[i] = from.xml_resources_[i];
      }
      for (int i = 0; i < urdf_resources_.length; ++i)
      {
         urdf_resources_[i] = from.urdf_resources_[i];
      }
      directory_.delete(0, directory_.length());
      directory_.insert(0, from.directory_);

   }

   public int getNumXmlResources()
   {
      return num_xml_resources_;
   }

   public void setNumXmlResources(int num_xml_resources_)
   {
      this.num_xml_resources_ = num_xml_resources_;
   }

   public int getNumUrdfResources()
   {
      return num_urdf_resources_;
   }

   public void setNumUrdfResources(int num_urdf_resources_)
   {
      this.num_urdf_resources_ = num_urdf_resources_;
   }

   public StringBuilder[] getXmlResources()
   {
      return xml_resources_;
   }

   public StringBuilder[] getUrdfResources()
   {
      return urdf_resources_;
   }

   public StringBuilder getDirectory()
   {
      return directory_;
   }

   public java.lang.String getDirectoryAsString()
   {
      return directory_.toString();
   }

   public void setDirectory(java.lang.String s)
   {
      this.directory_.delete(0, this.directory_.length());
      this.directory_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("HardwareResources {");
      builder.append("num_xml_resources_=");
      builder.append(num_xml_resources_);
      builder.append("num_urdf_resources_=");
      builder.append(num_urdf_resources_);
      builder.append("xml_resources_=");
      builder.append(java.util.Arrays.toString(xml_resources_));
      builder.append("urdf_resources_=");
      builder.append(java.util.Arrays.toString(urdf_resources_));
      builder.append("directory_=");
      builder.append(directory_.toString());

      builder.append("}");
      return builder.toString();
   }
}