/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Holds hardware status info of Alex
<p>Source (alex_msgs/HardwareStatus):
<pre>{@code
# Holds hardware status info of Alex

# Various fault info
bool robot_fault
bool motor_fault
bool missed_deadline_fault
bool working_counter_fault
bool bus_over_voltage_fault
bool bus_over_current_fault

# Important EtherCAT Stuff
uint32 working_counter_mismatch_count
uint32 missed_deadlines

# Power Management Board Information
float64 battery_charge_percetage
float64 estimated_runtime_minutes
bool bus_over_voltage_warning
bool bus_over_current_warning
float64 battery_voltage_volts
float64 battery_current_amps
float64 battery_power_watts
float64 power_supply_voltage_volts
float64 power_supply_current_amps
float64 power_supply_power_watts
float64 motor_bus_voltage_volts
float64 motor_bus_current_amps
float64 motor_bus_power_watts

# Joint States
ROSDeviceStatusProvider[<=100] device_status_providers}</pre>
*/
public class HardwareStatus implements ROS2Message<HardwareStatus>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::HardwareStatus_";

   /**
      Various fault info
   */
   private boolean robot_fault_;
   private boolean motor_fault_;
   private boolean missed_deadline_fault_;
   private boolean working_counter_fault_;
   private boolean bus_over_voltage_fault_;
   private boolean bus_over_current_fault_;
   /**
      Important EtherCAT Stuff
   */
   private int working_counter_mismatch_count_;
   private int missed_deadlines_;
   /**
      Power Management Board Information
   */
   private double battery_charge_percetage_;
   private double estimated_runtime_minutes_;
   private boolean bus_over_voltage_warning_;
   private boolean bus_over_current_warning_;
   private double battery_voltage_volts_;
   private double battery_current_amps_;
   private double battery_power_watts_;
   private double power_supply_voltage_volts_;
   private double power_supply_current_amps_;
   private double power_supply_power_watts_;
   private double motor_bus_voltage_volts_;
   private double motor_bus_current_amps_;
   private double motor_bus_power_watts_;
   /**
      Joint States
   */
   private final IDLObjectSequence<alex_msgs.ROSDeviceStatusProvider> device_status_providers_;

   public HardwareStatus()
   {
      robot_fault_ = (boolean) false;
      motor_fault_ = (boolean) false;
      missed_deadline_fault_ = (boolean) false;
      working_counter_fault_ = (boolean) false;
      bus_over_voltage_fault_ = (boolean) false;
      bus_over_current_fault_ = (boolean) false;
      bus_over_voltage_warning_ = (boolean) false;
      bus_over_current_warning_ = (boolean) false;
      device_status_providers_ = new IDLObjectSequence<alex_msgs.ROSDeviceStatusProvider>(0, 100, alex_msgs.ROSDeviceStatusProvider.class);

   }

   public HardwareStatus(HardwareStatus from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_fault_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // motor_fault_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // missed_deadline_fault_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // working_counter_fault_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // bus_over_voltage_fault_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // bus_over_current_fault_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // working_counter_mismatch_count_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // missed_deadlines_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // battery_charge_percetage_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // estimated_runtime_minutes_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // bus_over_voltage_warning_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // bus_over_current_warning_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // battery_voltage_volts_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // battery_current_amps_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // battery_power_watts_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // power_supply_voltage_volts_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // power_supply_current_amps_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // power_supply_power_watts_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // motor_bus_voltage_volts_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // motor_bus_current_amps_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // motor_bus_power_watts_
      currentAlignment += device_status_providers_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(robot_fault_);
      buffer.writeBoolean(motor_fault_);
      buffer.writeBoolean(missed_deadline_fault_);
      buffer.writeBoolean(working_counter_fault_);
      buffer.writeBoolean(bus_over_voltage_fault_);
      buffer.writeBoolean(bus_over_current_fault_);
      buffer.writeInt(working_counter_mismatch_count_);
      buffer.writeInt(missed_deadlines_);
      buffer.writeDouble(battery_charge_percetage_);
      buffer.writeDouble(estimated_runtime_minutes_);
      buffer.writeBoolean(bus_over_voltage_warning_);
      buffer.writeBoolean(bus_over_current_warning_);
      buffer.writeDouble(battery_voltage_volts_);
      buffer.writeDouble(battery_current_amps_);
      buffer.writeDouble(battery_power_watts_);
      buffer.writeDouble(power_supply_voltage_volts_);
      buffer.writeDouble(power_supply_current_amps_);
      buffer.writeDouble(power_supply_power_watts_);
      buffer.writeDouble(motor_bus_voltage_volts_);
      buffer.writeDouble(motor_bus_current_amps_);
      buffer.writeDouble(motor_bus_power_watts_);
      device_status_providers_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      robot_fault_ = buffer.readBoolean();
      motor_fault_ = buffer.readBoolean();
      missed_deadline_fault_ = buffer.readBoolean();
      working_counter_fault_ = buffer.readBoolean();
      bus_over_voltage_fault_ = buffer.readBoolean();
      bus_over_current_fault_ = buffer.readBoolean();
      working_counter_mismatch_count_ = buffer.readInt();
      missed_deadlines_ = buffer.readInt();
      battery_charge_percetage_ = buffer.readDouble();
      estimated_runtime_minutes_ = buffer.readDouble();
      bus_over_voltage_warning_ = buffer.readBoolean();
      bus_over_current_warning_ = buffer.readBoolean();
      battery_voltage_volts_ = buffer.readDouble();
      battery_current_amps_ = buffer.readDouble();
      battery_power_watts_ = buffer.readDouble();
      power_supply_voltage_volts_ = buffer.readDouble();
      power_supply_current_amps_ = buffer.readDouble();
      power_supply_power_watts_ = buffer.readDouble();
      motor_bus_voltage_volts_ = buffer.readDouble();
      motor_bus_current_amps_ = buffer.readDouble();
      motor_bus_power_watts_ = buffer.readDouble();
      device_status_providers_.deserialize(buffer);

   }

   @Override
   public void set(HardwareStatus from)
   {
      robot_fault_ = from.robot_fault_;
      motor_fault_ = from.motor_fault_;
      missed_deadline_fault_ = from.missed_deadline_fault_;
      working_counter_fault_ = from.working_counter_fault_;
      bus_over_voltage_fault_ = from.bus_over_voltage_fault_;
      bus_over_current_fault_ = from.bus_over_current_fault_;
      working_counter_mismatch_count_ = from.working_counter_mismatch_count_;
      missed_deadlines_ = from.missed_deadlines_;
      battery_charge_percetage_ = from.battery_charge_percetage_;
      estimated_runtime_minutes_ = from.estimated_runtime_minutes_;
      bus_over_voltage_warning_ = from.bus_over_voltage_warning_;
      bus_over_current_warning_ = from.bus_over_current_warning_;
      battery_voltage_volts_ = from.battery_voltage_volts_;
      battery_current_amps_ = from.battery_current_amps_;
      battery_power_watts_ = from.battery_power_watts_;
      power_supply_voltage_volts_ = from.power_supply_voltage_volts_;
      power_supply_current_amps_ = from.power_supply_current_amps_;
      power_supply_power_watts_ = from.power_supply_power_watts_;
      motor_bus_voltage_volts_ = from.motor_bus_voltage_volts_;
      motor_bus_current_amps_ = from.motor_bus_current_amps_;
      motor_bus_power_watts_ = from.motor_bus_power_watts_;
      device_status_providers_.set(from.device_status_providers_);

   }

   public boolean getRobotFault()
   {
      return robot_fault_;
   }

   public void setRobotFault(boolean robot_fault_)
   {
      this.robot_fault_ = robot_fault_;
   }

   public boolean getMotorFault()
   {
      return motor_fault_;
   }

   public void setMotorFault(boolean motor_fault_)
   {
      this.motor_fault_ = motor_fault_;
   }

   public boolean getMissedDeadlineFault()
   {
      return missed_deadline_fault_;
   }

   public void setMissedDeadlineFault(boolean missed_deadline_fault_)
   {
      this.missed_deadline_fault_ = missed_deadline_fault_;
   }

   public boolean getWorkingCounterFault()
   {
      return working_counter_fault_;
   }

   public void setWorkingCounterFault(boolean working_counter_fault_)
   {
      this.working_counter_fault_ = working_counter_fault_;
   }

   public boolean getBusOverVoltageFault()
   {
      return bus_over_voltage_fault_;
   }

   public void setBusOverVoltageFault(boolean bus_over_voltage_fault_)
   {
      this.bus_over_voltage_fault_ = bus_over_voltage_fault_;
   }

   public boolean getBusOverCurrentFault()
   {
      return bus_over_current_fault_;
   }

   public void setBusOverCurrentFault(boolean bus_over_current_fault_)
   {
      this.bus_over_current_fault_ = bus_over_current_fault_;
   }

   public int getWorkingCounterMismatchCount()
   {
      return working_counter_mismatch_count_;
   }

   public void setWorkingCounterMismatchCount(int working_counter_mismatch_count_)
   {
      this.working_counter_mismatch_count_ = working_counter_mismatch_count_;
   }

   public int getMissedDeadlines()
   {
      return missed_deadlines_;
   }

   public void setMissedDeadlines(int missed_deadlines_)
   {
      this.missed_deadlines_ = missed_deadlines_;
   }

   public double getBatteryChargePercetage()
   {
      return battery_charge_percetage_;
   }

   public void setBatteryChargePercetage(double battery_charge_percetage_)
   {
      this.battery_charge_percetage_ = battery_charge_percetage_;
   }

   public double getEstimatedRuntimeMinutes()
   {
      return estimated_runtime_minutes_;
   }

   public void setEstimatedRuntimeMinutes(double estimated_runtime_minutes_)
   {
      this.estimated_runtime_minutes_ = estimated_runtime_minutes_;
   }

   public boolean getBusOverVoltageWarning()
   {
      return bus_over_voltage_warning_;
   }

   public void setBusOverVoltageWarning(boolean bus_over_voltage_warning_)
   {
      this.bus_over_voltage_warning_ = bus_over_voltage_warning_;
   }

   public boolean getBusOverCurrentWarning()
   {
      return bus_over_current_warning_;
   }

   public void setBusOverCurrentWarning(boolean bus_over_current_warning_)
   {
      this.bus_over_current_warning_ = bus_over_current_warning_;
   }

   public double getBatteryVoltageVolts()
   {
      return battery_voltage_volts_;
   }

   public void setBatteryVoltageVolts(double battery_voltage_volts_)
   {
      this.battery_voltage_volts_ = battery_voltage_volts_;
   }

   public double getBatteryCurrentAmps()
   {
      return battery_current_amps_;
   }

   public void setBatteryCurrentAmps(double battery_current_amps_)
   {
      this.battery_current_amps_ = battery_current_amps_;
   }

   public double getBatteryPowerWatts()
   {
      return battery_power_watts_;
   }

   public void setBatteryPowerWatts(double battery_power_watts_)
   {
      this.battery_power_watts_ = battery_power_watts_;
   }

   public double getPowerSupplyVoltageVolts()
   {
      return power_supply_voltage_volts_;
   }

   public void setPowerSupplyVoltageVolts(double power_supply_voltage_volts_)
   {
      this.power_supply_voltage_volts_ = power_supply_voltage_volts_;
   }

   public double getPowerSupplyCurrentAmps()
   {
      return power_supply_current_amps_;
   }

   public void setPowerSupplyCurrentAmps(double power_supply_current_amps_)
   {
      this.power_supply_current_amps_ = power_supply_current_amps_;
   }

   public double getPowerSupplyPowerWatts()
   {
      return power_supply_power_watts_;
   }

   public void setPowerSupplyPowerWatts(double power_supply_power_watts_)
   {
      this.power_supply_power_watts_ = power_supply_power_watts_;
   }

   public double getMotorBusVoltageVolts()
   {
      return motor_bus_voltage_volts_;
   }

   public void setMotorBusVoltageVolts(double motor_bus_voltage_volts_)
   {
      this.motor_bus_voltage_volts_ = motor_bus_voltage_volts_;
   }

   public double getMotorBusCurrentAmps()
   {
      return motor_bus_current_amps_;
   }

   public void setMotorBusCurrentAmps(double motor_bus_current_amps_)
   {
      this.motor_bus_current_amps_ = motor_bus_current_amps_;
   }

   public double getMotorBusPowerWatts()
   {
      return motor_bus_power_watts_;
   }

   public void setMotorBusPowerWatts(double motor_bus_power_watts_)
   {
      this.motor_bus_power_watts_ = motor_bus_power_watts_;
   }

   public IDLObjectSequence<alex_msgs.ROSDeviceStatusProvider> getDeviceStatusProviders()
   {
      return device_status_providers_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("HardwareStatus {");
      builder.append("robot_fault_=");
      builder.append(robot_fault_);
      builder.append("motor_fault_=");
      builder.append(motor_fault_);
      builder.append("missed_deadline_fault_=");
      builder.append(missed_deadline_fault_);
      builder.append("working_counter_fault_=");
      builder.append(working_counter_fault_);
      builder.append("bus_over_voltage_fault_=");
      builder.append(bus_over_voltage_fault_);
      builder.append("bus_over_current_fault_=");
      builder.append(bus_over_current_fault_);
      builder.append("working_counter_mismatch_count_=");
      builder.append(working_counter_mismatch_count_);
      builder.append("missed_deadlines_=");
      builder.append(missed_deadlines_);
      builder.append("battery_charge_percetage_=");
      builder.append(battery_charge_percetage_);
      builder.append("estimated_runtime_minutes_=");
      builder.append(estimated_runtime_minutes_);
      builder.append("bus_over_voltage_warning_=");
      builder.append(bus_over_voltage_warning_);
      builder.append("bus_over_current_warning_=");
      builder.append(bus_over_current_warning_);
      builder.append("battery_voltage_volts_=");
      builder.append(battery_voltage_volts_);
      builder.append("battery_current_amps_=");
      builder.append(battery_current_amps_);
      builder.append("battery_power_watts_=");
      builder.append(battery_power_watts_);
      builder.append("power_supply_voltage_volts_=");
      builder.append(power_supply_voltage_volts_);
      builder.append("power_supply_current_amps_=");
      builder.append(power_supply_current_amps_);
      builder.append("power_supply_power_watts_=");
      builder.append(power_supply_power_watts_);
      builder.append("motor_bus_voltage_volts_=");
      builder.append(motor_bus_voltage_volts_);
      builder.append("motor_bus_current_amps_=");
      builder.append(motor_bus_current_amps_);
      builder.append("motor_bus_power_watts_=");
      builder.append(motor_bus_power_watts_);
      builder.append("device_status_providers_=");
      builder.append(device_status_providers_);

      builder.append("}");
      return builder.toString();
   }
}