/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Holds the state of the IMU
<p>Source (alex_msgs/IMUState):
<pre>{@code
# Holds the state of the IMU

string<=32 sensor_name

# Sensor Data
float64[4] quaternion
float64[3] gyroscope
float64[3] accelerometer

# Sensor Status
int32 temperature
bool is_operational}</pre>
*/
public class IMUState implements ROS2Message<IMUState>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::IMUState_";

   // Note: The length of this string should not exceed 32 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder sensor_name_;
   /**
      Sensor Data
   */
   private final double[] quaternion_;
   private final double[] gyroscope_;
   private final double[] accelerometer_;
   /**
      Sensor Status
   */
   private int temperature_;
   private boolean is_operational_;

   public IMUState()
   {
      sensor_name_ = new StringBuilder(32);
      quaternion_ = new double[4];
      gyroscope_ = new double[3];
      accelerometer_ = new double[3];
      is_operational_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * sensor_name_.length()) + 1; // sensor_name_
      currentAlignment += (4 * 8) + CDRBuffer.alignment(currentAlignment, (4 * 8)); // quaternion_
      currentAlignment += (3 * 8) + CDRBuffer.alignment(currentAlignment, (3 * 8)); // gyroscope_
      currentAlignment += (3 * 8) + CDRBuffer.alignment(currentAlignment, (3 * 8)); // accelerometer_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // temperature_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_operational_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(sensor_name_);
      for (int i = 0; i < quaternion_.length; ++i)
      {
         buffer.writeDouble(quaternion_[i]);
      }
      for (int i = 0; i < gyroscope_.length; ++i)
      {
         buffer.writeDouble(gyroscope_[i]);
      }
      for (int i = 0; i < accelerometer_.length; ++i)
      {
         buffer.writeDouble(accelerometer_[i]);
      }
      buffer.writeInt(temperature_);
      buffer.writeBoolean(is_operational_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(sensor_name_);
      for (int i = 0; i < quaternion_.length; ++i)
      {
         quaternion_[i] = buffer.readDouble();
      }
      for (int i = 0; i < gyroscope_.length; ++i)
      {
         gyroscope_[i] = buffer.readDouble();
      }
      for (int i = 0; i < accelerometer_.length; ++i)
      {
         accelerometer_[i] = buffer.readDouble();
      }
      temperature_ = buffer.readInt();
      is_operational_ = buffer.readBoolean();

   }

   @Override
   public void set(IMUState from)
   {
      sensor_name_.delete(0, sensor_name_.length());
      sensor_name_.insert(0, from.sensor_name_);
      for (int i = 0; i < quaternion_.length; ++i)
      {
         quaternion_[i] = from.quaternion_[i];
      }
      for (int i = 0; i < gyroscope_.length; ++i)
      {
         gyroscope_[i] = from.gyroscope_[i];
      }
      for (int i = 0; i < accelerometer_.length; ++i)
      {
         accelerometer_[i] = from.accelerometer_[i];
      }
      temperature_ = from.temperature_;
      is_operational_ = from.is_operational_;

   }

   public StringBuilder getSensorName()
   {
      return sensor_name_;
   }

   public java.lang.String getSensorNameAsString()
   {
      return sensor_name_.toString();
   }

   public void setSensorName(java.lang.String s)
   {
      this.sensor_name_.delete(0, this.sensor_name_.length());
      this.sensor_name_.insert(0, s);
   }
   public double[] getQuaternion()
   {
      return quaternion_;
   }

   public double[] getGyroscope()
   {
      return gyroscope_;
   }

   public double[] getAccelerometer()
   {
      return accelerometer_;
   }

   public int getTemperature()
   {
      return temperature_;
   }

   public void setTemperature(int temperature_)
   {
      this.temperature_ = temperature_;
   }

   public boolean getIsOperational()
   {
      return is_operational_;
   }

   public void setIsOperational(boolean is_operational_)
   {
      this.is_operational_ = is_operational_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("IMUState {");
      builder.append("sensor_name_=");
      builder.append(sensor_name_.toString());
      builder.append("quaternion_=");
      builder.append(java.util.Arrays.toString(quaternion_));
      builder.append("gyroscope_=");
      builder.append(java.util.Arrays.toString(gyroscope_));
      builder.append("accelerometer_=");
      builder.append(java.util.Arrays.toString(accelerometer_));
      builder.append("temperature_=");
      builder.append(temperature_);
      builder.append("is_operational_=");
      builder.append(is_operational_);

      builder.append("}");
      return builder.toString();
   }
}