/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
One frame of labelled motion-capture markers, as Motive streams them.

Consumed by alex-mocap's NatNetMocapSource, which reconstructs per-link poses by
registering each marker cluster against its calibrated layout. See MOCAP_STREAMING.md
in this directory for the publisher contract, including the two conventions below that
are silent when wrong.

FRAME. Positions are metres in Motive's world frame W, Z-UP. Motive streams Y-up by
default; set Streaming -> Up Axis to Z-Up, or rotate before publishing. A Y-up stream
produces a plausible, wrong reconstruction rather than an error.

NOT GRAVITY-ALIGNED. Do not apply any floor-tilt correction here. That correction is a
measured session constant applied downstream (alex-mocap F8, TiltMeasurement); baking it
into the stream makes it invisible and unrecorded.
<p>Source (alex_msgs/MocapMarkerArray):
<pre>{@code
# One frame of labelled motion-capture markers, as Motive streams them.
#
# Consumed by alex-mocap's NatNetMocapSource, which reconstructs per-link poses by
# registering each marker cluster against its calibrated layout. See MOCAP_STREAMING.md
# in this directory for the publisher contract, including the two conventions below that
# are silent when wrong.
#
# FRAME. Positions are metres in Motive's world frame W, Z-UP. Motive streams Y-up by
# default; set Streaming -> Up Axis to Z-Up, or rotate before publishing. A Y-up stream
# produces a plausible, wrong reconstruction rather than an error.
#
# NOT GRAVITY-ALIGNED. Do not apply any floor-tilt correction here. That correction is a
# measured session constant applied downstream (alex-mocap F8, TiltMeasurement); baking it
# into the stream makes it invisible and unrecorded.

# Motive's frame timestamp. Must share an epoch with the robot's encoder stream, or the
# reconstructed pose silently lags whatever it is compared against. Publish the transmit
# time if Motive's own timestamp cannot be resolved to that epoch, and say so.
uint64 timestamp_nanoseconds

# Motive's frame counter. Gaps here separate "the network dropped a frame" from "Motive
# stopped sending", which are otherwise indistinguishable at the consumer.
uint32 frame_number

# The three sequences below are parallel and MUST be the same length: entry i of
# `position` and `visible` describes marker `motive_id[i]`. A consumer that sees them
# disagree drops the whole frame.

# Stable per-marker identifier, consistent across frames, matching the consumer's
# labelling file. For markers in a Motive asset this is the packed (model_id << 16) |
# marker_id; for point-cloud markers it is the streaming id. Either is fine as long as it
# is stable and the labelling file agrees.
int32[<=256] motive_id

# Marker position in W. Ignored when the corresponding `visible` is false; publishing NaN
# there is encouraged but not required.
geometry_msgs/Point[<=256] position

# False when Motive did not actually see the marker this frame -- occluded, or solved by
# the asset rather than observed. A marker may also simply be omitted from all three
# sequences, which means the same thing.
#
# What must NOT happen is publishing a stale or model-solved position with visible=true.
# The consumer's rigidity and conditioning gates cannot detect an invented marker, and a
# cluster completed by three real markers and one invented one registers cleanly to the
# wrong pose.
bool[<=256] visible
}</pre>
*/
public class MocapMarkerArray implements ROS2Message<MocapMarkerArray>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::MocapMarkerArray_";

   /**
      Motive's frame timestamp. Must share an epoch with the robot's encoder stream, or the
      reconstructed pose silently lags whatever it is compared against. Publish the transmit
      time if Motive's own timestamp cannot be resolved to that epoch, and say so.
   */
   private long timestamp_nanoseconds_;
   /**
      Motive's frame counter. Gaps here separate "the network dropped a frame" from "Motive
      stopped sending", which are otherwise indistinguishable at the consumer.
   */
   private int frame_number_;
   /**
      Stable per-marker identifier, consistent across frames, matching the consumer's
      labelling file. For markers in a Motive asset this is the packed (model_id << 16) |
      marker_id; for point-cloud markers it is the streaming id. Either is fine as long as it
      is stable and the labelling file agrees.
   */
   private final IDLIntSequence motive_id_;
   /**
      Marker position in W. Ignored when the corresponding `visible` is false; publishing NaN
      there is encouraged but not required.
   */
   private final IDLObjectSequence<geometry_msgs.Point> position_;
   /**
      False when Motive did not actually see the marker this frame -- occluded, or solved by
      the asset rather than observed. A marker may also simply be omitted from all three
      sequences, which means the same thing.

      What must NOT happen is publishing a stale or model-solved position with visible=true.
      The consumer's rigidity and conditioning gates cannot detect an invented marker, and a
      cluster completed by three real markers and one invented one registers cleanly to the
      wrong pose.
   */
   private final IDLBoolSequence visible_;

   public MocapMarkerArray()
   {
      motive_id_ = new IDLIntSequence(0, 256);
      position_ = new IDLObjectSequence<geometry_msgs.Point>(0, 256, geometry_msgs.Point.class);
      visible_ = new IDLBoolSequence(0, 256);

   }

   public MocapMarkerArray(MocapMarkerArray from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // timestamp_nanoseconds_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // frame_number_
      currentAlignment += motive_id_.calculateSizeBytes(currentAlignment);
      currentAlignment += position_.calculateSizeBytes(currentAlignment);
      currentAlignment += visible_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(timestamp_nanoseconds_);
      buffer.writeInt(frame_number_);
      motive_id_.serialize(buffer);
      position_.serialize(buffer);
      visible_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      timestamp_nanoseconds_ = buffer.readLong();
      frame_number_ = buffer.readInt();
      motive_id_.deserialize(buffer);
      position_.deserialize(buffer);
      visible_.deserialize(buffer);

   }

   @Override
   public void set(MocapMarkerArray from)
   {
      timestamp_nanoseconds_ = from.timestamp_nanoseconds_;
      frame_number_ = from.frame_number_;
      motive_id_.set(from.motive_id_);
      position_.set(from.position_);
      visible_.set(from.visible_);

   }

   public long getTimestampNanoseconds()
   {
      return timestamp_nanoseconds_;
   }

   public void setTimestampNanoseconds(long timestamp_nanoseconds_)
   {
      this.timestamp_nanoseconds_ = timestamp_nanoseconds_;
   }

   public int getFrameNumber()
   {
      return frame_number_;
   }

   public void setFrameNumber(int frame_number_)
   {
      this.frame_number_ = frame_number_;
   }

   public IDLIntSequence getMotiveId()
   {
      return motive_id_;
   }

   public IDLObjectSequence<geometry_msgs.Point> getPosition()
   {
      return position_;
   }

   public IDLBoolSequence getVisible()
   {
      return visible_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("MocapMarkerArray {");
      builder.append("timestamp_nanoseconds_=");
      builder.append(timestamp_nanoseconds_);
      builder.append("frame_number_=");
      builder.append(frame_number_);
      builder.append("motive_id_=");
      builder.append(motive_id_);
      builder.append("position_=");
      builder.append(position_);
      builder.append("visible_=");
      builder.append(visible_);

      builder.append("}");
      return builder.toString();
   }
}