/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Holds info for each 1DOF controlled Joint
<p>Source (alex_msgs/OneDOFJointState):
<pre>{@code
# Holds info for each 1DOF controlled Joint

string<=35 joint_name

# Joint Data
float64 q
float64 qd
float64 tau

# Actuator statuses
float64 act_temp
bool is_operational}</pre>
*/
public class OneDOFJointState implements ROS2Message<OneDOFJointState>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::OneDOFJointState_";

   // Note: The length of this string should not exceed 35 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder joint_name_;
   /**
      Joint Data
   */
   private double q_;
   private double qd_;
   private double tau_;
   /**
      Actuator statuses
   */
   private double act_temp_;
   private boolean is_operational_;

   public OneDOFJointState()
   {
      joint_name_ = new StringBuilder(35);
      is_operational_ = (boolean) false;

   }

   public OneDOFJointState(OneDOFJointState from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * joint_name_.length()) + 1; // joint_name_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // q_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // qd_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // tau_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // act_temp_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_operational_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(joint_name_);
      buffer.writeDouble(q_);
      buffer.writeDouble(qd_);
      buffer.writeDouble(tau_);
      buffer.writeDouble(act_temp_);
      buffer.writeBoolean(is_operational_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(joint_name_);
      q_ = buffer.readDouble();
      qd_ = buffer.readDouble();
      tau_ = buffer.readDouble();
      act_temp_ = buffer.readDouble();
      is_operational_ = buffer.readBoolean();

   }

   @Override
   public void set(OneDOFJointState from)
   {
      joint_name_.delete(0, joint_name_.length());
      joint_name_.insert(0, from.joint_name_);
      q_ = from.q_;
      qd_ = from.qd_;
      tau_ = from.tau_;
      act_temp_ = from.act_temp_;
      is_operational_ = from.is_operational_;

   }

   public StringBuilder getJointName()
   {
      return joint_name_;
   }

   public java.lang.String getJointNameAsString()
   {
      return joint_name_.toString();
   }

   public void setJointName(java.lang.String s)
   {
      this.joint_name_.delete(0, this.joint_name_.length());
      this.joint_name_.insert(0, s);
   }
   public double getQ()
   {
      return q_;
   }

   public void setQ(double q_)
   {
      this.q_ = q_;
   }

   public double getQd()
   {
      return qd_;
   }

   public void setQd(double qd_)
   {
      this.qd_ = qd_;
   }

   public double getTau()
   {
      return tau_;
   }

   public void setTau(double tau_)
   {
      this.tau_ = tau_;
   }

   public double getActTemp()
   {
      return act_temp_;
   }

   public void setActTemp(double act_temp_)
   {
      this.act_temp_ = act_temp_;
   }

   public boolean getIsOperational()
   {
      return is_operational_;
   }

   public void setIsOperational(boolean is_operational_)
   {
      this.is_operational_ = is_operational_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("OneDOFJointState {");
      builder.append("joint_name_=");
      builder.append(joint_name_.toString());
      builder.append("q_=");
      builder.append(q_);
      builder.append("qd_=");
      builder.append(qd_);
      builder.append("tau_=");
      builder.append(tau_);
      builder.append("act_temp_=");
      builder.append(act_temp_);
      builder.append("is_operational_=");
      builder.append(is_operational_);

      builder.append("}");
      return builder.toString();
   }
}