/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Sets the desireds for controlling each 1DOF joint
<p>Source (alex_msgs/OneDOFJointCommand):
<pre>{@code
# Sets the desireds for controlling each 1DOF joint

string<=35 joint_name

# Joint Desireds
float64 q_des
float64 qd_des
float64 tau_des
float64 stiffness
float64 damping
float64 max_position_error
float64 max_velocity_error
float64 max_torque

# Enable Actuator Command
bool enable

# Joint control type, 0 is Position, 1 is Velocity, 2 is Effort, 3 disables the control
byte joint_control_type}</pre>
*/
public class OneDOFJointCommand implements ROS2Message<OneDOFJointCommand>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::OneDOFJointCommand_";

   // Note: The length of this string should not exceed 35 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder joint_name_;
   /**
      Joint Desireds
   */
   private double q_des_;
   private double qd_des_;
   private double tau_des_;
   private double stiffness_;
   private double damping_;
   private double max_position_error_;
   private double max_velocity_error_;
   private double max_torque_;
   /**
      Enable Actuator Command
   */
   private boolean enable_;
   /**
      Joint control type, 0 is Position, 1 is Velocity, 2 is Effort, 3 disables the control
   */
   private byte joint_control_type_;

   public OneDOFJointCommand()
   {
      joint_name_ = new StringBuilder(35);
      enable_ = (boolean) false;

   }

   public OneDOFJointCommand(OneDOFJointCommand from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * joint_name_.length()) + 1; // joint_name_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // q_des_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // qd_des_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // tau_des_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // stiffness_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // damping_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // max_position_error_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // max_velocity_error_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // max_torque_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // enable_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // joint_control_type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(joint_name_);
      buffer.writeDouble(q_des_);
      buffer.writeDouble(qd_des_);
      buffer.writeDouble(tau_des_);
      buffer.writeDouble(stiffness_);
      buffer.writeDouble(damping_);
      buffer.writeDouble(max_position_error_);
      buffer.writeDouble(max_velocity_error_);
      buffer.writeDouble(max_torque_);
      buffer.writeBoolean(enable_);
      buffer.writeByte(joint_control_type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(joint_name_);
      q_des_ = buffer.readDouble();
      qd_des_ = buffer.readDouble();
      tau_des_ = buffer.readDouble();
      stiffness_ = buffer.readDouble();
      damping_ = buffer.readDouble();
      max_position_error_ = buffer.readDouble();
      max_velocity_error_ = buffer.readDouble();
      max_torque_ = buffer.readDouble();
      enable_ = buffer.readBoolean();
      joint_control_type_ = buffer.readByte();

   }

   @Override
   public void set(OneDOFJointCommand from)
   {
      joint_name_.delete(0, joint_name_.length());
      joint_name_.insert(0, from.joint_name_);
      q_des_ = from.q_des_;
      qd_des_ = from.qd_des_;
      tau_des_ = from.tau_des_;
      stiffness_ = from.stiffness_;
      damping_ = from.damping_;
      max_position_error_ = from.max_position_error_;
      max_velocity_error_ = from.max_velocity_error_;
      max_torque_ = from.max_torque_;
      enable_ = from.enable_;
      joint_control_type_ = from.joint_control_type_;

   }

   public StringBuilder getJointName()
   {
      return joint_name_;
   }

   public java.lang.String getJointNameAsString()
   {
      return joint_name_.toString();
   }

   public void setJointName(java.lang.String s)
   {
      this.joint_name_.delete(0, this.joint_name_.length());
      this.joint_name_.insert(0, s);
   }
   public double getQDes()
   {
      return q_des_;
   }

   public void setQDes(double q_des_)
   {
      this.q_des_ = q_des_;
   }

   public double getQdDes()
   {
      return qd_des_;
   }

   public void setQdDes(double qd_des_)
   {
      this.qd_des_ = qd_des_;
   }

   public double getTauDes()
   {
      return tau_des_;
   }

   public void setTauDes(double tau_des_)
   {
      this.tau_des_ = tau_des_;
   }

   public double getStiffness()
   {
      return stiffness_;
   }

   public void setStiffness(double stiffness_)
   {
      this.stiffness_ = stiffness_;
   }

   public double getDamping()
   {
      return damping_;
   }

   public void setDamping(double damping_)
   {
      this.damping_ = damping_;
   }

   public double getMaxPositionError()
   {
      return max_position_error_;
   }

   public void setMaxPositionError(double max_position_error_)
   {
      this.max_position_error_ = max_position_error_;
   }

   public double getMaxVelocityError()
   {
      return max_velocity_error_;
   }

   public void setMaxVelocityError(double max_velocity_error_)
   {
      this.max_velocity_error_ = max_velocity_error_;
   }

   public double getMaxTorque()
   {
      return max_torque_;
   }

   public void setMaxTorque(double max_torque_)
   {
      this.max_torque_ = max_torque_;
   }

   public boolean getEnable()
   {
      return enable_;
   }

   public void setEnable(boolean enable_)
   {
      this.enable_ = enable_;
   }

   public byte getJointControlType()
   {
      return joint_control_type_;
   }

   public void setJointControlType(byte joint_control_type_)
   {
      this.joint_control_type_ = joint_control_type_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("OneDOFJointCommand {");
      builder.append("joint_name_=");
      builder.append(joint_name_.toString());
      builder.append("q_des_=");
      builder.append(q_des_);
      builder.append("qd_des_=");
      builder.append(qd_des_);
      builder.append("tau_des_=");
      builder.append(tau_des_);
      builder.append("stiffness_=");
      builder.append(stiffness_);
      builder.append("damping_=");
      builder.append(damping_);
      builder.append("max_position_error_=");
      builder.append(max_position_error_);
      builder.append("max_velocity_error_=");
      builder.append(max_velocity_error_);
      builder.append("max_torque_=");
      builder.append(max_torque_);
      builder.append("enable_=");
      builder.append(enable_);
      builder.append("joint_control_type_=");
      builder.append(joint_control_type_);

      builder.append("}");
      return builder.toString();
   }
}