/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package alex_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Data holder containing status info for a given device
<p>Source (alex_msgs/ROSDeviceStatusProvider):
<pre>{@code
# Data holder containing status info for a given device

# The device name
string<=70 name

# Primary device status info
bool is_responding
bool is_faulted
byte ethercat_state

# More specific device status info related to isFaulted (elmo twitter fault)
bool under_voltage
bool over_voltage
bool sto_disabled
bool current_short
bool over_temp
# uint32 elmo_error_code TODO
# float64 input_encoder_error TODO
# float64 output_encoder_error TODO
# float64 output_encoder_error TODO}</pre>
*/
public class ROSDeviceStatusProvider implements ROS2Message<ROSDeviceStatusProvider>
{
   public static final java.lang.String name = "alex_msgs::msg::dds_::ROSDeviceStatusProvider_";

   /**
      The device name
   */
   // Note: The length of this string should not exceed 70 characters.
   // This is not strictly enforced in Java / jros2.
   private final StringBuilder name_;
   /**
      Primary device status info
   */
   private boolean is_responding_;
   private boolean is_faulted_;
   private byte ethercat_state_;
   /**
      More specific device status info related to isFaulted (elmo twitter fault)
   */
   private boolean under_voltage_;
   private boolean over_voltage_;
   private boolean sto_disabled_;
   private boolean current_short_;
   private boolean over_temp_;

   public ROSDeviceStatusProvider()
   {
      name_ = new StringBuilder(70);
      is_responding_ = (boolean) false;
      is_faulted_ = (boolean) false;
      under_voltage_ = (boolean) false;
      over_voltage_ = (boolean) false;
      sto_disabled_ = (boolean) false;
      current_short_ = (boolean) false;
      over_temp_ = (boolean) false;

   }

   public ROSDeviceStatusProvider(ROSDeviceStatusProvider from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_responding_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_faulted_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // ethercat_state_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // under_voltage_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // over_voltage_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // sto_disabled_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // current_short_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // over_temp_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(name_);
      buffer.writeBoolean(is_responding_);
      buffer.writeBoolean(is_faulted_);
      buffer.writeByte(ethercat_state_);
      buffer.writeBoolean(under_voltage_);
      buffer.writeBoolean(over_voltage_);
      buffer.writeBoolean(sto_disabled_);
      buffer.writeBoolean(current_short_);
      buffer.writeBoolean(over_temp_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(name_);
      is_responding_ = buffer.readBoolean();
      is_faulted_ = buffer.readBoolean();
      ethercat_state_ = buffer.readByte();
      under_voltage_ = buffer.readBoolean();
      over_voltage_ = buffer.readBoolean();
      sto_disabled_ = buffer.readBoolean();
      current_short_ = buffer.readBoolean();
      over_temp_ = buffer.readBoolean();

   }

   @Override
   public void set(ROSDeviceStatusProvider from)
   {
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      is_responding_ = from.is_responding_;
      is_faulted_ = from.is_faulted_;
      ethercat_state_ = from.ethercat_state_;
      under_voltage_ = from.under_voltage_;
      over_voltage_ = from.over_voltage_;
      sto_disabled_ = from.sto_disabled_;
      current_short_ = from.current_short_;
      over_temp_ = from.over_temp_;

   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }
   public boolean getIsResponding()
   {
      return is_responding_;
   }

   public void setIsResponding(boolean is_responding_)
   {
      this.is_responding_ = is_responding_;
   }

   public boolean getIsFaulted()
   {
      return is_faulted_;
   }

   public void setIsFaulted(boolean is_faulted_)
   {
      this.is_faulted_ = is_faulted_;
   }

   public byte getEthercatState()
   {
      return ethercat_state_;
   }

   public void setEthercatState(byte ethercat_state_)
   {
      this.ethercat_state_ = ethercat_state_;
   }

   public boolean getUnderVoltage()
   {
      return under_voltage_;
   }

   public void setUnderVoltage(boolean under_voltage_)
   {
      this.under_voltage_ = under_voltage_;
   }

   public boolean getOverVoltage()
   {
      return over_voltage_;
   }

   public void setOverVoltage(boolean over_voltage_)
   {
      this.over_voltage_ = over_voltage_;
   }

   public boolean getStoDisabled()
   {
      return sto_disabled_;
   }

   public void setStoDisabled(boolean sto_disabled_)
   {
      this.sto_disabled_ = sto_disabled_;
   }

   public boolean getCurrentShort()
   {
      return current_short_;
   }

   public void setCurrentShort(boolean current_short_)
   {
      this.current_short_ = current_short_;
   }

   public boolean getOverTemp()
   {
      return over_temp_;
   }

   public void setOverTemp(boolean over_temp_)
   {
      this.over_temp_ = over_temp_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ROSDeviceStatusProvider {");
      builder.append("name_=");
      builder.append(name_.toString());
      builder.append("is_responding_=");
      builder.append(is_responding_);
      builder.append("is_faulted_=");
      builder.append(is_faulted_);
      builder.append("ethercat_state_=");
      builder.append(ethercat_state_);
      builder.append("under_voltage_=");
      builder.append(under_voltage_);
      builder.append("over_voltage_=");
      builder.append(over_voltage_);
      builder.append("sto_disabled_=");
      builder.append(sto_disabled_);
      builder.append("current_short_=");
      builder.append(current_short_);
      builder.append("over_temp_=");
      builder.append(over_temp_);

      builder.append("}");
      return builder.toString();
   }
}